config/routes.rb
Newton::Application.routes.draw do

  namespace :admin do 
    resources :posts do
      post '_preview', :on => :collection, :as => 'preview'
    end  

    resources :drafts, :controller => "posts", :draft => true
    
    resources :pages do
      post '_preview', :on => :collection, :as => 'preview'
    end
    
    resources :comments
    resources :settings, :except => [ :show, :edit, :update ] do
      put 'update', :on => :collection
    end

    root :to => 'posts#index'
  end

  match ':year/:month/:slug' => 'posts#show', :year => /2\d{3}/, :month => /\d{1,2}/, :as => 'post'
  match '/pages/:slug' => 'pages#show', :as => 'page'
  match '/archives/:year/:month' => 'posts#list', :year => /2\d{3}/, :month => /\d{2}/, :as => 'archives_by_month'
  match '/archives/tag/:tag' => 'posts#list', :as => 'archives_by_tag'
  match '/archives/:type' => 'posts#list', :as => 'archives_by_type', :type => /\w*/

  root :to => 'posts#index'
end

app/views/admin/pages/_form.html.erb
<%= hidden_field_tag 'resource_action', 'save' %>
	
<% if @page.errors.any? %>
	<div class="errors">
		<h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

		<ul>
			<% @page.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div id="page_meta" class="clearfix">
	<div class="field">
		<label style="display: block;">
			<div class="field_label">
				Title
			</div>
			
			<div class="field_value text">
				<%= f.text_field :title, :class => 'title' %>
			</div>
		</label>
	</div>
	
	<div class="field">
		<label>
			<div class="field_label">
				Slug
			</div>
			
			<div class="field_value text">
				<%= f.text_field :slug, :class => 'slug', 'data-validators' => 'page_slug' %>
			</div>
		</label>
	</div>
</div>


<div id="editor_wrapper">
	<div id="save_notice" style="display: none;">
		<span>saved</span>
	</div>

	<%= f.hidden_field :body %>
	<div id="editor" style="width: 100%; height: 400px; position: relative; background-color: #fff;"><%= @page.body %></div>
</div>
	
<div id="page_actions" class="actions">
	<% if @page.published? %>
		<p>This page was published on <%= @page.published_at.getlocal.strftime('%F at %r') %>.</p>
 		<input data-action="save" type="button" value="Save" />
		<input data-action="unpublish" type="button" value="Save &amp; Unpublish" />
	<% else %>
		<p>This page has not been published.</p>
		<input data-action="save" type="button" value="Save as Draft" />
		<input data-action="save_and_publish" type="button" value="Save &amp; Publish" />
	<% end %>

	<% unless @page.new_record? %>
		<input data-action="destroy" type="button" value="Delete" />
	<% end %>
</div>

app/views/admin/pages/edit.html.erb
<div id="PageForm">
	<%= form_for([:admin, @page], :url => { :action => 'update' }) do |f| %>
		<%= render :partial => 'form', :locals => { :f => f } %>
	<% end %>
</div>

<div id="ResourcePreview">
	<h2>Preview</h2>
	
	<div id="ResourcePreview_Body"></div>
</div>


<script type="text/javascript" charset="utf-8">
	$(function() {
		resource_form = $('#edit_page_<%= @page.id %>');
		resource_body_element = $('#page_body');
		
		<% if @autosave_url %>
			auto_save_url = '<%= @autosave_url %>';
		<% end %>

		preview_url = '<%= preview_admin_pages_url %>';
		
		initNewton();
	});
</script>

app/views/admin/pages/index.html.erb
<h1>Pages</h1>

<div id="PageList" class="admin_list">
	<table>
		<thead>
			<tr>
				<th class="page_title">Title</th>
				<th class="page_status">Status</th>
				<th class="page_date">Created</th>
			</tr>
		</thead>
		
		<tbody>
			<% @pages.each do |p| %>
				<tr class="page">
					<td class="page_title"><%= link_to(p.title, edit_admin_page_url(p)) %></td>
					<td class="page_status"><%= p.published? ? 'Published' : 'Draft' %></td>
					<td class="page_date"><%= p.created_at.getlocal.strftime('<span title="%c">%F</span>').html_safe %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	
	<% if @pages.blank? %>
		<p>You currently don't have any pages.</p>
	<% end %>

	<div class="actions">
		<%= link_to('New Page', new_admin_page_url, :class => 'button') %>
	</div>
</div>

app/views/admin/pages/new.html.erb
<div id="PageForm">
	<%= form_for([:admin, @page], :url => { :action => 'create' }) do |f| %>
		<%= render :partial => 'form', :locals => { :f => f } %>
	<% end %>
</div>

<div id="ResourcePreview">
	<h2>Preview</h2>
	
	<div id="ResourcePreview_Body"></div>
</div>

<script type="text/javascript" charset="utf-8">
	$(function() {
		resource_form = $('#new_page');
		resource_body_element = $('#page_body');

		preview_url = '<%= preview_admin_pages_url %>';
		
		initNewton();
	});
</script>