config/routes.rb
Newton::Application.routes.draw do

  namespace :admin do 
    resources :posts do
      post '_preview', :on => :collection, :as => 'preview'
    end  

    resources :drafts, :controller => "posts", :draft => true
    
    resources :pages do
      post '_preview', :on => :collection, :as => 'preview'
    end
    
    resources :comments
    resources :settings, :except => [ :show, :edit, :update ] do
      put 'update', :on => :collection
    end

    root :to => 'posts#index'
  end

  match ':year/:month/:slug' => 'posts#show', :year => /2\d{3}/, :month => /\d{1,2}/, :as => 'post'
  match '/pages/:slug' => 'pages#show', :as => 'page'
  match '/archives/:year/:month' => 'posts#list', :year => /2\d{3}/, :month => /\d{2}/, :as => 'archives_by_month'
  match '/archives/tag/:tag' => 'posts#list', :as => 'archives_by_tag'
  match '/archives/:type' => 'posts#list', :as => 'archives_by_type', :type => /\w*/

  root :to => 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :slug, :post_type, :body, :published_at
  
  validates :title, :slug, :post_type, :presence => true
  validates :body, :presence => { :message => "can't be blank for published posts" }, :if => "published_at.present?"
  validates :slug, :format => { :with => /^[a-z0-9\-]*$/, :message => "contains invalid characters for a post slug" }
  validates :post_type, :inclusion => { :in => %w(link prose picture video), :message => "is not a valid post type" }
  
  scope :draft, where('published_at IS NULL')
  scope :published, where('published_at IS NOT NULL')

  scope :published_in_year_and_month, lambda { |year, month| where("published_at IS NOT NULL AND published_at BETWEEN datetime('#{year}-#{"%02d" % month.to_i}-01 00:00:00') AND datetime('#{year}-#{"%02d" % month.to_i}-01 00:00:00','start of month','+1 month','-0.001 second')") }
  
  def published?
    self.published_at.present?
  end
  
  def html
    @_html ||= Redcarpet::Render::SmartyPants.render(MD_PARSER.render(self.body))
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_filter :is_request_for_drafts?
  cache_sweeper :post_sweeper, :only => [ :create, :update, :destroy ]

  def index
    if @for_drafts
      @posts = Post.draft.order('title ASC')
    else
      @posts = Post.published.order('published_at DESC')
    end
  end
  
  def new
    if flash[:post].present?
      @post = flash[:post]
    else
      @post = Post.new
    end
    
    @autosave_url = nil
  end
  
  def create
    @post = Post.new(params[:post])
    
    if params[:resource_action] == 'publish'
      @post.published_at = Time.new
    end
    
    if @post.save
      if @post.published?
        redirect_to admin_posts_url
      else
        redirect_to admin_drafts_url
      end
    else
      @post.published_at = nil
      flash[:post] = @post

      redirect_to new_admin_draft_url
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    
    if @post.published?
      @autosave_url = nil
    else
      @autosave_url = admin_draft_url(@post)
    end
  end
  
  def _preview
    post = Post.new(:body => params[:body])
    render :json => { :html => post.html }
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])
    
    if params[:resource_action] == 'publish'
      @post.published_at = Time.new
    elsif params[:resource_action] == 'unpublish'
      @post.published_at = nil
    end
    
    if @post.save
      respond_to do |format|
        format.html do
          if @post.published?
            redirect_to admin_posts_url
          else
            redirect_to admin_drafts_url
          end
        end

        format.json  { render :json => { :success => true } }
      end
    else
      @post.published_at = @post.published_at_was if @post.published_at_changed?
      flash[:post] = @post
      
      if @post.published?
        redirect_to edit_admin_post_url(@post)
      else
        redirect_to edit_admin_draft_url(@post)
      end
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    
    @post.destroy
    
    if @post.published?
      destination = admin_posts_url
    else
      destination = admin_drafts_url
    end
    
    respond_to do |format|
      format.html { redirect_to destination }
      format.json { render :json => { :success => true, :redirect_to => destination } }
    end
  end
  
  private
  
  def is_request_for_drafts?
    @for_drafts = params[:draft].present?
    
    return @for_drafts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  caches_page :index, :show
  
  def index
    @posts = Post.published.order('published_at DESC').limit(10)
  end
  
  def list
    if params[:year].present? && params[:month].present?
      @title = "Posts by Month: #{Time.local(params[:year], params[:month]).strftime('%B %Y')}"
      @posts = Post.published.where(["published_at BETWEEN ? AND ?", Time.local(params[:year], params[:month]), Time.local(params[:year], params[:month]).end_of_month]).order('published_at DESC')
    elsif params[:tag].present?
      # to be implemented
    elsif params[:type].present?
      @title = "Posts by Type: #{params[:type].capitalize}"
      @posts = Post.published.where({ :post_type => params[:type] }).order('published_at DESC').limit(10)
    end
  end
  
  def show
    if params[:slug].present?
      @post = Post.published_in_year_and_month(params[:year], params[:month]).where({ :slug => params[:slug] }).first
    end

    if @post.present?
      if params[:month].length == 1
        redirect_to(post_url(:year => @post.published_at.year, :month => @post.published_at.month.to_s.rjust(2, '0'), :slug => @post.slug), :status => :moved_permanently) and return
      end
    else
      raise ActiveRecord::RecordNotFound
    end
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def no_posts_excuse
    [
      # (I was/I've) probably (been) too busy...
      "watching <a href=\"http://www.youtube.com/watch?v=DpLF8yLlcK4\" rel=\"nofollow\">this cat video</a> on YouTube",
      "trying to <a href=\"http://megaswf.com/serve/102223/\" rel=\"nofollow\">build a better automobile</a>",
      # add your own
    ].sample.html_safe
  end
end

app/views/admin/posts/_form.html.erb
<%= hidden_field_tag 'resource_action', 'save' %>
	
<% if @post.errors.any? %>
	<div class="errors">
		<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div id="post_meta" class="clearfix">
	<div class="field full">
		<label style="display: block;">
			<div class="field_label">
				Title
			</div>
			
			<div class="field_value text">
				<%= f.text_field :title, :class => 'title' %>
			</div>
		</label>
	</div>
	
	<div class="field full">
		<label>
			<div class="field_label">
				Slug
			</div>
			
			<div class="field_value text">
				<%= f.text_field :slug, :class => 'slug', 'data-validators' => 'post_slug' %>
			</div>
		</label>
	</div>

	<div class="field half">
		<label>
			<div class="field_label">
				Type
			</div>
			
			<div class="field_value select">
				<%= f.select :post_type, post_types, :selected => (@post.post_type rescue ['Prose', 'prose']) %>
			</div>
		</label>
	</div>

	<% if @post.published? %>
		<div class="field full">
			<label>
				<div class="field_label">
					Published At
				</div>
			
				<div class="field_value date">
					<%= f.datetime_select :published_at, :default => @post.published_at.getlocal %>
				</div>
			</label>
		</div>
	<% end %>
</div>


<div id="editor_wrapper">
	<div id="save_notice" style="display: none;">
		<span>saved</span>
	</div>

	<%= f.hidden_field :body %>
	<div id="editor" style="width: 100%; height: 400px; position: relative; background-color: #fff;"><%= @post.body %></div>
</div>
	
<div id="post_actions" class="actions">
	<% if @post.published? %>
		<input data-action="save" type="button" value="Save" />
		<input data-action="unpublish" type="button" value="Save &amp; Unpublish" />
	<% else %>
		<p>This post has not yet been published.</p>
		<input data-action="save" type="button" value="Save" />
		<input data-action="save_and_publish" type="button" value="Save &amp; Publish" />
	<% end %>
	
	<% unless @post.new_record? %>
		<input data-action="destroy" type="button" value="Delete" />
	<% end %>
</div>

app/views/admin/posts/edit.html.erb
<div id="PostForm">
	<%= form_for([:admin, @post], :url => { :action => 'update', :draft => !@post.published? }) do |f| %>
		<%= render :partial => 'form', :locals => { :f => f } %>
	<% end %>
</div>

<div id="ResourcePreview">
	<h2>Preview</h2>
	
	<div id="ResourcePreview_Body"></div>
</div>

<script type="text/javascript" charset="utf-8">
	$(function() {
		resource_form = $('#edit_post_<%= @post.id %>');
		resource_body_element = $('#post_body');

		<% if @autosave_url %>
			auto_save_url = '<%= @autosave_url %>';
		<% end %>
		
		preview_url = '<%= preview_admin_posts_url %>';
		
		initNewton();
	});
</script>

app/views/admin/posts/index.html.erb
<% if @for_drafts %>
	<h1>Drafts</h1>
<% else %>
	<h1>Posts</h1>
<% end %>

<div id="PostList" class="admin_list">
	<table>
		<thead>
			<tr>
				<th class="post_title">Title</th>
				<th class="post_type">Type</th>
				<% if @for_drafts %>
					<th class="post_date">Created</th>
				<% else %>
					<th class="post_date">Published</th>
				<% end %>
			</tr>
		</thead>
		
		<tbody>
			<% @posts.each do |p| %>
				<tr class="post">
					<td class="post_title"><%= link_to(p.title, p.published? ? edit_admin_post_url(p) : edit_admin_draft_url(p)) %></td>
					<td class="post_type"><%= p.post_type.capitalize %></td>
					<td class="post_date"><%= (p.published? ? p.published_at : p.created_at).getlocal.strftime('<span title="%c">%F</span>').html_safe %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	
	<% if @posts.blank? %>
		<% if @for_drafts %>
			<p>You currently don't have any draft posts.</p>
		<% else %>
			<p>You currently don't have any published posts.</p>
		<% end %>
	<% end %>

	<div class="actions">
		<%= link_to('New Draft', new_admin_draft_url, :class => 'button') %>
	</div>
	
</div>

app/views/admin/posts/new.html.erb
<div id="PostForm">
	<%= form_for([:admin, @post], :url => { :action => 'create', :draft => true }) do |f| %>
		<%= render :partial => 'form', :locals => { :f => f } %>
	<% end %>
</div>

<div id="ResourcePreview">
	<h2>Preview</h2>
	
	<div id="ResourcePreview_Body"></div>
</div>

<script type="text/javascript" charset="utf-8">
	$(function() {
		resource_form = $('#new_post');
		resource_body_element = $('#post_body');

		preview_url = '<%= preview_admin_posts_url %>';
		
		initNewton();
	});
</script>