config/routes.rb
Newton::Application.routes.draw do

  namespace :admin do 
    resources :posts do
      post '_preview', :on => :collection, :as => 'preview'
    end  

    resources :drafts, :controller => "posts", :draft => true
    
    resources :pages do
      post '_preview', :on => :collection, :as => 'preview'
    end
    
    resources :comments
    resources :settings, :except => [ :show, :edit, :update ] do
      put 'update', :on => :collection
    end

    root :to => 'posts#index'
  end

  match ':year/:month/:slug' => 'posts#show', :year => /2\d{3}/, :month => /\d{1,2}/, :as => 'post'
  match '/pages/:slug' => 'pages#show', :as => 'page'
  match '/archives/:year/:month' => 'posts#list', :year => /2\d{3}/, :month => /\d{2}/, :as => 'archives_by_month'
  match '/archives/tag/:tag' => 'posts#list', :as => 'archives_by_tag'
  match '/archives/:type' => 'posts#list', :as => 'archives_by_type', :type => /\w*/

  root :to => 'posts#index'
end

app/views/layouts/admin.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">

	<title><%= @page_title.present? ? "#{@page_title} &mdash; admin: #{@blog_title}".html_safe : "admin: #{@blog_title.html_safe}" %></title>

	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">

	<%= stylesheet_link_tag "admin", :media => "all" %>

	<%= javascript_include_tag "admin", "/ace/ace", "/ace/mode-markdown" %>
	
    <%= csrf_meta_tags %>
</head>

<body class="admin">
	<header>

	</header>

	<aside role="nav">
		<nav role="admin">
			<ul>
				<li class="<%= 'active' if controller.controller_name == 'posts' && !@for_drafts && controller.action_name != 'new' %>"><%= link_to(admin_posts_url, :title => "Published Posts") do %><i class="icon-bullhorn"></i><% end %></li>
				<li class="<%= 'active' if controller.controller_name == 'posts' && @for_drafts && controller.action_name != 'new' %>"><%= link_to(admin_drafts_url, :title => "Draft Posts") do %><i class="icon-cloud"></i><% end %></li>
				<li class="<%= 'active' if controller.controller_name == 'posts' && controller.action_name == 'new' %>"><%= link_to(new_admin_draft_url, :title => "New Post") do %><i class="icon-plus-sign"></i><% end %></li>
				<li class="<%= 'active' if controller.controller_name == 'pages' %>"><%= link_to(admin_pages_url, :title => "Pages") do %><i class="icon-book"></i><% end %></li>
				<!-- <li class="<%= 'active' if controller.controller_name == 'comments' %>"><%= link_to(admin_comments_url, :title => "Comments") do %><i class="icon-comments"></i><% end %></li> -->
				<li class="<%= 'active' if controller.controller_name == 'settings' %>"><%= link_to(admin_settings_url, :title => "Settings") do %><i class="icon-cog"></i><% end %></li>
			</ul>
		</nav>
	</aside>

	<div role="main" class="clearfix">
		<% if @page_title.present? %>
			<h1><%= @page_title %></h1>
		<% end %>
		
		<% if flash[:notice] %>
			<p class="notice"><%= flash[:notice] %></p>
		<% end %>

		<% if flash[:error] %>
			<p class="error"><%= flash[:error] %></p>
		<% end %>
		
		<%= yield %>
	</div>

	<footer>
		<p class="copyright">
			&copy; <%= Time.new.year %> &mdash; Original work licensed under a 
			<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/" title="Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported">Creative Commons License</a>.
		</p>
	</footer>
</body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8">

	<title><%= @page_title.present? ? "#{@page_title} &mdash; #{@blog_title}".html_safe : @blog_title.html_safe %></title>

	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">

	<%= stylesheet_link_tag "application", :media => "all" %>

  <%= csrf_meta_tags %>
</head>

<body>
	<header>

	</header>

	<aside role="nav">
		<nav role="home">
			<%= link_to(root_url) do %>
				<i class="icon-home"></i>
			<% end %>
		</nav>
		
		<nav role="meta">
			<ul>
				<li>Hello.</li>
				<li>This is.</li>
				<li>A place to put.</li>
				<li>Some information.</li>
				<li>About yourself.</li>
			</ul>
		</nav>
		
		<nav role="meta-dynamic">
			<ul>
				<li>You can put.</li>
				<li>More frequently changing.</li>
				<li>Information here.</li>
			</ul>
		</nav>
		
		<nav role="archives">
			<ul>
				<li>Other posts <%= link_to('this month', archives_by_month_url(:year => Time.new.year, :month => Time.new.strftime("%m"))) %>.</li>
				<li>Archives for <%= link_to('last month', archives_by_month_url(:year => 1.month.ago.year, :month => 1.month.ago.strftime("%m"))) %>.</li>
			</ul>
		</nav>
	</aside>

	<div role="main">
		<%= yield %>
	</div>

	<footer>
		<p class="copyright">
			&copy; <%= Time.new.year %> &mdash; Original work licensed under a 
			<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/" title="Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported">Creative Commons (BY-NC-SA 3.0) License</a>.
		</p>
	</footer>
  
  <aside role="supplemental">
    
  </aside>

	<!-- If you want to use Google Analytics, update and uncomment the code below. -->
	<!-- 
	<script>
		var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
		(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
		g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
		s.parentNode.insertBefore(g,s)}(document,'script'));
	</script>
	-->
</body>
</html>